# Generated by Django 4.2.7 on 2024-02-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='name',
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_desc',
            field=models.CharField(default='nodesc', max_length=250),
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_name',
            field=models.CharField(default='nodesc', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_threads',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
